jobs:
  - name: createBBManifest
    type: manifest
    steps:
      - GET busybox

  - name: createNginxManifest
    type: manifest
    steps:
      - GET nginx

  - name: createAlpineManifest
    type: manifest
    steps:
      - GET alpine

  - name : deployToEcs
    type: ecsDeploy
    steps:
      - GET createNginxManifest
