jobs:
  - name: createBBManifest
    type: manifest
    steps:
      - GET busyboxImage

  - name: createNginxManifest
    type: manifest
    steps:
      - GET nginxImage

  - name: createAlpineManifest
    type: manifest
    steps:
      - GET alpineImage

  - name : deployToEcs
    type: ecsDeploy
    steps:
      - GET createNginxManifest
      - GET ecsTestCluster
