jobs:
  - name: createBBManifest
    type: manifest
    steps:
      - GET busybox

  - name: createNginxManifest
    type: manifest
    steps:
      - GET nginx
      - PUT busybox

  - name : deployToEcs
    type: ecsDeploy
    steps:
      - GET: createNginxManifest
